### ISSUE TITLE
Use with Unity3D

### ISSUE THREAD

**Issue by sidhants** [sahb1239/SAHB.GraphQLClient#73]
Just exploring if someone has tried using this library with the Unity Game Engine?

**Comment by sahb1239** [comment]
I have not tried it myself but it should be compatible since Unity should support [.NET Standard 2.0](https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-implementation-support).

Currently SAHB.GraphQL.Client and SAHB.GraphQL.Client.Introspection supports .NET Standard 1.2 while SAHB.GraphQL.Client.Subscription supports .NET Standard 2.0.

I would be happy to hear how your experience with the client is and if you have any issues with using the client.

**Comment by sahb1239** [comment]
I will close this issue. If you have any issues you are welcome to open this issue again.

**Comment by ClarenceMG** [comment]
Can I use this library with Xamarin iOS?

**Comment by sahb1239** [comment]
> Can I use this library with Xamarin iOS?

@ClarenceMG Since it's .NET Standard 1.2 you should be able to use it. If you have any problems you are welcome to create a issue.
