### ISSUE TITLE
Add CancellationToken support

### ISSUE THREAD

**Issue by bddckr** [sahb1239/SAHB.GraphQLClient#88]
It would be great to be able to cancel `IGraphQLHttpExecutor.ExecuteQuery` and also anything that calls into it.

This should be as "easy" as just adding (optional?) `CancellationToken` parameters everywhere, yet it's quite a large number of API to adjust. 🙂

**Comment by sahb1239** [comment]
I think it should be handled by providing a overloaded method for each method which supports cancellation in the IGraphQLHttpClient class. Everywhere else this could be a required, since client could mostly should use the IGraphQLHttpClient interface directly. 

As you are saying this would be a quite large number of API's to adjust and will result in breaking changes and will therefore be in a 3.0 release of the library.

Would you be willing to provide a pull request for this change? I will then plan a 3.0 release of the library in the coming weeks.

**Comment by bddckr** [comment]
I raised a PR in #90 with the changes that I did in my local testing.

I added optional parameters instead of offering an overload just for the sake of adding the cancellation token. Thankfully a `default` `CancellationToken` is equivalent to `CancellationToken.None` and thus callers would only notice a change if they called the changed methods without specifying _named_ arguments, due to this change changing the order of the `params` `headers` parameter.

So while it's still a breaking change I believe there is no need to provide overloaded methods. I'm happy to change the PR to use overloads instead of the current solution of just adding a new default parameter, so let me know what you think!

I may have missed some API that should offer cancellation, let me know if I did and I'll add it.
